version: '3.8'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb

  rest_api:
    build: .
    command: uvicorn src.rest_api:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    env_file:
      - .env
    depends_on:
      - localstack

  youtube_query_scanner:
    build: .
    command: python src/youtube_query_scanner.py
    volumes:
      - .:/app
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    env_file:
      - .env
    depends_on:
      - localstack