version: '3.8'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"            # LocalStack Edge Proxy
      - "8080:8080"            # LocalStack Dashboard
    environment:
      - SERVICES=dynamodb     # Only enable DynamoDB
      - DEBUG=1
      - DATA_DIR=/tmp/localstack_data
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/sbecker11/localstack_data:/tmp/localstack_data  # Use your preferred path for data